### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by MuhsinunC** [BillyGalbreath/Pl3xMap-Signs#1]
There is no wiki on this. I attempted to place a sign down with the following text:
[pl3xmap]
test

and it did not create a sign marker on the webmap. How is this plugin intended to be used?

**Comment by BillyGalbreath** [comment]
Hold a map in your hand and right click a sign to add it. Left click to remove it.

Permission node required: `pl3xmap.signs.admin`
